### ISSUE TITLE
decimal lever_rate instead of integer in Huobi.Net.Clients.HuobiClient.UsdtMarginSwapApi.Trading.PlaceCrossMarginOrderAsync and PlaceIsolatedMarginOrderAsync

### ISSUE THREAD

**Issue by Antik94** [JKorf/Huobi.Net#100]
**Describe the bug**
Huobi server expecting integer value on place of lever_rate.
Functions from title receive leverageRate parameter in decimal format, so in request for Huobi server we get **"{\"lever_rate\":5.0}"** instead of **"{\"lever_rate\":5}"** (for example)

When executing the request, we get constant error _1067 The lever_rate field is invalid. Please re-enter_

**To Reproduce**
Huobi.Net.Clients.HuobiClient.UsdtMarginSwapApi.Trading.PlaceCrossMarginOrderAsync(0.001, OrderSide.Buy, 5, "BTC-USDT")

**Expected behavior**
Expecting successful WebCallResult

**Comment by JKorf** [comment]
Has been fixed in the latest version

**Comment by Antik94** [comment]
Much appriciated!
