### ISSUE TITLE
need add new OrderSideConverter and OrderTypeConverter and new OrderType Enums

### ISSUE THREAD

**Issue by wecando168** [JKorf/Huobi.Net#109]
**Describe the bug**
If there is a grid transaction order in the synchronized order, the correct direction of the grid transaction order cannot be obtained

**To Reproduce**
Huobi.Net/Converters/OrderSideConverter.cs
need add:
            new KeyValuePair<OrderSide, string>(OrderSide.Buy, "buy-limit-grid"), 
            new KeyValuePair<OrderSide, string>(OrderSide.Sell, "sell-limit-grid") 

Huobi.Net/Converters/OrderTypeConverter.cs
Huobi.Net/Enums/OrderType.cs

Corresponding types and conversions need to be provided for "buy-limit-grid" and "sell-limit-grid"

**Comment by wecando168** [comment]
In addition, there are two "OrderTypes" that need to be added for grid transactions
Buy market grid
Sell market grid

**Comment by JKorf** [comment]
Added the grid types to the converters and enums in the latest version
