### ISSUE TITLE
GetOrdersAsync filters don't work

### ISSUE THREAD

**Issue by apollo4040** [JKorf/Huobi.Net#11]
Hello!
I'm using Huobi. Net v1.0.1 and it seems like filters in method GetOrdersAsync don't work. 

I have 2 orders in my history 
id ...52783 and ...54950 
Here is my code:
`long? startOrderId = null;
var lastHuobiResult = await client.GetOrdersAsync(symbol, Enum.GetValues(typeof(HuobiOrderState)).Cast<HuobiOrderState>(), null, null, null, startOrderId, limit);`
when I'm setting startOrderId > firstHistoryOrder.Id: I'm getting first history order

Then I tried another approach:
`DateTime startDate = DateTime.MinValue;
DateTime finishDate = DateTime.MaxValue;
var lastHuobiResult = await client.GetOrdersAsync(symbol, Enum.GetValues(typeof(HuobiOrderState)).Cast<HuobiOrderState>(), null, startDate, finishDate, null, limit);` 

I'm tying to set my startDate > than FinishedAt date of my first history order. And I'm also getting first history order. Even is my startDate grater then FinishedAt more than 100ms. 

Is this issue related to library or to exchange?

**Comment by apollo4040** [comment]
Seems like date filter isn't working. But fromId filter is OK

**Comment by JKorf** [comment]
I don't have any funds on Huobi at the moment, so it's a bit hard to check for me. Could you put LogVerbosity to Debug in the options and check what is send to the server?

**Comment by lucaswalter** [comment]
Hello, I am running into the same issue when trying to filter by the most recent OrderId.

Here is how I am calling it (and then incrementing the orderId by 1 from the most recent trade):
`
await client.GetSymbolTradesAsync(map.ProductOnExchange, types: types, startTime: startTime, endTime: null, fromId: orderId, limit: MAX_PAGE_SIZE)
`

According to their api documentation the 'direct' parameter will default to **both** when not specified. Is it possible that is causing the issue with filtering by fromId here?

https://huobiapi.github.io/docs/v1/en/#search-match-results


From the logs, it is making a GET request to this url and is still returning trades with an orderId less than the **fromId** provided:  https://api.huobi.pro/v1/order/matchresults?AccessKeyId=9d160e0a-b4fc1aec-31129e0b-mn8ikls4qg&from=33104725139&SignatureMethod=HmacSHA256&SignatureVersion=2&size=5&start-date=2013-01-01&symbol=ethusdt&Timestamp=2019-05-15T04%3A29%3A22&types=buy-limit%2Csell-limit%2Cbuy-market%2Csell-market%2Cbuy-ioc%2Csell-ioc%2Cbuy-limit-maker%2Csell-limit-maker&Signature=MxYjf79AHm%2BVdghjAkhS33nCcDOFpvPQi2CT%2BSUAB1U%3D 


Response with ids before the fromId:

`
{  
   "status":"ok",
   "data":[  
      {  
         "symbol":"ethusdt",
         "filled-points":"0.0",
         "order-id":33104725138,
         "source":"spot-web",
         "match-id":101084829570,
         "created-at":1557883071773,
         "filled-fees":"0.0001626",
         "filled-amount":"0.0813",
         "price":"222.05",
         "id":5647257576,
         "type":"buy-limit"
      },
      {  
         "symbol":"ethusdt",
         "filled-points":"0.0",
         "order-id":33104507643,
         "source":"spot-web",
         "match-id":101084815149,
         "created-at":1557882932710,
         "filled-fees":"0.04953276",
         "filled-amount":"0.1115",
         "price":"222.12",
         "id":5647211987,
         "type":"sell-market"
      },
      {  
         "symbol":"ethusdt",
         "filled-points":"0.0",
         "order-id":33104503386,
         "source":"spot-web",
         "match-id":101084814759,
         "created-at":1557882930133,
         "filled-fees":"0.000223421627525991",
         "filled-amount":"0.111710813762995634",
         "price":"222.19",
         "id":5647211106,
         "type":"buy-market"
      },
      {  
         "symbol":"ethusdt",
         "filled-points":"0.0",
         "order-id":33104500317,
         "source":"spot-web",
         "match-id":101084814447,
         "created-at":1557882928193,
         "filled-fees":"0.055038858",
         "filled-amount":"0.1239",
         "price":"222.11",
         "id":5647210674,
         "type":"sell-market"
      },
      {  
         "symbol":"ethusdt",
         "filled-points":"0.0",
         "order-id":33104500317,
         "source":"spot-web",
         "match-id":101084814447,
         "created-at":1557882928193,
         "filled-fees":"0.011283188",
         "filled-amount":"0.0254",
         "price":"222.11",
         "id":5647210673,
         "type":"sell-market"
      }
   ]
}
`

**Comment by JKorf** [comment]
@lucaswalter Thanks for the research and additional information! I've pushed a new version 1.1.1 in which I've added some parameters which were missing, including the `direct` parameter. Please let me know if this fixes the issue.

**Comment by lucaswalter** [comment]
Thank you very much, testing this now!

**Comment by JKorf** [comment]
Assuming this is fixed, if not let me know.
