### ISSUE TITLE
Amount serialization issue in PlaceOrderAsync

### ISSUE THREAD

**Issue by samz-me** [JKorf/Huobi.Net#12]
For amount with value `1` serialized  as `1.0` Huobi api returns `order-orderamount-precision-error, order amount precision error, scale: 0` 

The issue is exist only for symbols with quantity step size 1 like elfbtc.

As a temporary fix, I replaced `{ "amount", amount }` to `{ "amount", amount.ToString() }`

**Comment by JKorf** [comment]
Hi thanks for the report. It's a bit odd since 1.0 is the standard since it makes it clear it's a decimal and not an int. Anyway, it should be fixed in the latest version available in a few minutes.

**Comment by samz-me** [comment]
Hi. Great. Thank you!
