### ISSUE TITLE
Can you merge HuobiOpenOrder and HuobiOrder?

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Huobi.Net#18]
These classes contain the same information.

**Comment by samz-me** [comment]
Hi

Actually the classes are not the same. 
We also have one more class HuobiOrderUpdate .
I added IHuobiOrder interface to simplify access to common members.

https://github.com/GenesisVision/Huobi.Net/blob/gv-dev/Huobi.Net/Interfaces/IHuobiOrder.cs

@JKorf I can send pull request if you agree to add it.

**Comment by NektoDron** [comment]
But this interface doesn't present in the library
https://www.screencast.com/t/rro8bxEPRY9j

**Comment by NektoDron** [comment]
I'm sorry. I did not see that this fork.
