### ISSUE TITLE
Doesn't work with Huobi Russia

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Huobi.Net#20]
The Huobi Russia has another API URL
https://www.huobi.com.ru/api

The library can't make valid signature for this URL.
Because you should remove "/api" part of path.

I made some changes in the HuobiAuthenticationProvider class and it works fine.

`            var absolutePath = uriObj.AbsolutePath;
            if (absolutePath.StartsWith("/api"))
                absolutePath = absolutePath.Substring(4);
            signData += absolutePath + "\n";
`

**Comment by JKorf** [comment]
Hi, I've added the fix you suggested in the latest version.
