### ISSUE TITLE
Enum updates

### ISSUE THREAD

**Issue by burakoner** [JKorf/Huobi.Net#21]
Huobi supports 4Hours Klines. can you add please?

HuobiEnums.cs
`    public enum HuobiPeriod
    {
        OneMinute,
        FiveMinutes,
        FifteenMinutes,
        ThirtyMinutes,
        OneHour,
        FourHour,
        OneDay,
        OneWeek,
        OneMonth,
        OneYear
    }`

and
PeriodConverter.cs
`        protected override List<KeyValuePair<HuobiPeriod, string>> Mapping => new List<KeyValuePair<HuobiPeriod, string>>
        {
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.OneMinute, "1min"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.FiveMinutes, "5min"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.FifteenMinutes, "15min"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.ThirtyMinutes, "30min"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.OneHour, "60min"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.FourHour, "4hour"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.OneDay, "1day"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.OneWeek, "1week"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.OneMonth, "1mon"),
            new KeyValuePair<HuobiPeriod, string>(HuobiPeriod.OneYear, "1year")
        };`

**Comment by JKorf** [comment]
Hi Burak, it has been added in the latest version.
