### ISSUE TITLE
Signed Public Requests

### ISSUE THREAD

**Issue by burakoner** [JKorf/Huobi.Net#22]
Hi @JKorf 

I had rate limit problems before, I got rate limit errors even I use proper limits. I talked with Huobi Technical Team and they recommended to use api keys even public data requests. I downloaded your huobi reposity and tried signed public requests. for example getklines. and woowww, it works.

I am sure many people suffer from this problem and they cant reach huobi technical team. Is it possible to add an option in huobiclientoptions as below
"If api credentials are exist, send signed requests for public endpoints"

Have a nice day.

**Comment by JKorf** [comment]
Hi, I added it in the latest version, thanks for the research!
