### ISSUE TITLE
Huobi symbols

### ISSUE THREAD

**Issue by apollo4040** [JKorf/Huobi.Net#25]
Hi!
Have you seen that symbols model was extended? 
Here are the example:
{"base-currency":"powr","quote-currency":"eth","price-precision":8,"amount-precision":0,"symbol-partition":"innovation","symbol":"powreth","state":"online","value-precision":8,"min-order-amt":0.1,"max-order-amt":500000,"min-order-value":0.001}

As you can see here are couple of new fields:
"state":"online",
"value-precision":8,
"min-order-amt":0.1,
"max-order-amt":500000,
"min-order-value":0.001

I don't know what's the purpose of this fields, but maybe you can update HuobiSymbol class?

**Comment by JKorf** [comment]
Pushed a new version, should be available in a few minutes.
