### ISSUE TITLE
HuobiBalanceType missing some types

### ISSUE THREAD

**Issue by 97686773** [JKorf/Huobi.Net#27]
about huobiclient ，when i call GetBalancesAsync  I got an error:
Cannot map enum. Type: Huobi.Net.Objects.HuobiBalanceType, Value: loan
2019/06/27 21:59:24:916 | Error | Deserialize JsonSerializationException: Error setting value to 'Type' on 'Huobi.Net.Objects.HuobiBalance'.. Received data: 
{
  "status": "ok",
  "data": {
    "id": 3474679,
    "type": "margin",
    "state": "working",
    "list": [
      {
        "currency": "btc",
        "type": "trade",
        "balance": "0.0000000062984"
      },
      {
        "currency": "btc",
        "type": "frozen",
        "balance": "0"
      },
      {
        "currency": "btc",
        "type": "**loan**",
        "balance": "0"
      },
      {
        "currency": "btc",
        "type": "**interest**",
        "balance": "0"
      },

the type include loan and interest
Maybe you should add these two types to the HuobiBalanceType .

**Comment by JKorf** [comment]
Hi, thanks for the report. I've added those and pushed a new version, 1.1.4 should be available in a few minutes!
