### ISSUE TITLE
Could you update the library for CryptoExchange.Net 2.1.8?

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Huobi.Net#32]
It generates MissingMethodException if I try to connect.

**Comment by NektoDron** [comment]
I see that there should be a second parameter ArrayParametersSerialization.MultipleValues for CreateParamString calls.

**Comment by JKorf** [comment]
Thanks for the report, I missed the update was a breaking change for the Huobi implementation. I've pushed a new version, should be available in a few minutes.
