### ISSUE TITLE
Authentication failed: Server error: No response from server

### ISSUE THREAD

**Issue by sndnnlfhvk** [JKorf/Huobi.Net#34]
When I use Websocket access to anonymous endpoints such as "SubscribeToKlineUpdatesAsync",it works well,but when I access to authenticated endpoints such as "SubscribeToOrderUpdatesAsync"、"SubscribeToAccountUpdatesAsync",the server response:
Authentication failed: Server error: No response from server 。
 HuobiSocketClientOptions huobiSocketClientOptions = new HuobiSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(_apiKey, _apiSecret)
            };          
            using (HuobiSocketClient huobiSocketClient = new HuobiSocketClient(huobiSocketClientOptions))
{
 .......
}

I use the same key and secret access to HuobiClient(Rest),it works well.

**Comment by JKorf** [comment]
Hi, you're right. With the latest refactoring 2 parameters got switched around. I've fixed the issue and pushed a new version, should be available in a few minutes. 
Thanks for the report, let me know if you run into any other problems.

**Comment by sndnnlfhvk** [comment]
Thanks a lot. I've tried the new version and it works well.
