### ISSUE TITLE
GetAccounts() Error

### ISSUE THREAD

**Issue by miuo** [JKorf/Huobi.Net#36]
private static void GetAccountBalances(Huobi.Net.HuobiClient client)
        {
           client.SetApiCredentials("***", "***"); // Change to your credentials
           var accounts = client.GetAccounts();

Sir, when i used in this way,  i cann't got the right feedback information,  error msg show as below: 
"Error deserializing data"

how can i fix this?

**Comment by gensleralexander** [comment]
@JKorf I can confirm this error, I got the same. (both async and sync)
Problem seems that the method is expected to return IEnumerable<HuobiAccountBalance>, although it should return IEnumerable<HuobiAccount>.

**Comment by JKorf** [comment]
Hi, I've pushed a fix for this. For me it wasn't throwing errors with `IEnumerable<HuobiAccountBalance>`, but you're right, it should be `IEnumerable<HuobiAccount>`. 
Let me know if the latest version works for you.
