### ISSUE TITLE
ClientOrderId Support

### ISSUE THREAD

**Issue by burakoner** [JKorf/Huobi.Net#37]
Huobi supports client-order-id parameter when placing new order, with new API releases.
https://huobiapi.github.io/docs/spot/v1/en/#change-log

Could you please add support ClientOrderId parameter to Requests and Responses in Huobi.Net

[Request] Placing New Order
https://huobiapi.github.io/docs/spot/v1/en/#place-a-new-order

[Request & Response] Placing Batch Orders
https://huobiapi.github.io/docs/spot/v1/en/#place-a-batch-of-orders

[Request] Cancelling an Order
https://huobiapi.github.io/docs/spot/v1/en/#submit-cancel-for-an-order-based-on-client-order-id

[Request & Response] Cancelling Multiple Orders
https://huobiapi.github.io/docs/spot/v1/en/#submit-cancel-for-multiple-orders-by-ids

[Response] Getting All Open Orders
https://huobiapi.github.io/docs/spot/v1/en/#get-all-open-orders

[Response] Getting Details for an Order
https://huobiapi.github.io/docs/spot/v1/en/#get-the-order-detail-of-an-order
https://huobiapi.github.io/docs/spot/v1/en/#get-the-order-detail-of-an-order-based-on-client-order-id

[Response] Getting Order History
https://huobiapi.github.io/docs/spot/v1/en/#search-past-orders
https://huobiapi.github.io/docs/spot/v1/en/#search-historical-orders-within-48-hours

**Comment by JKorf** [comment]
Implemented in latest version

**Comment by mirror222** [comment]
Any updates for placing Batch Orders?

thank you.
