### ISSUE TITLE
Huobi GetTickers missing fields

### ISSUE THREAD

**Issue by Gustavobbr** [JKorf/Huobi.Net#39]
Hi,
The returning of GetTickers aren't bringing some fields.

It should return the following structure    {"symbol":"creusdt","open":0.002164,"high":0.00233,"low":0.002141,"close":0.002273,"amount":1.907087512791328E8,"vol":421097.89436649525,"count":5083,"bid":0.002273,"bidSize":105032.78,"ask":0.002275,"askSize":880000.0}

and it's returning the following fields only {
  Amount | 67657173.06086831 |
  Close | 0.0000003189 | 
  High | 0.0000003441 | 
  Low | 0.0000002916 | 
  Open | 0.0000003317 | 
  Symbol | "tnbbtc" | 
  TradeCount | 4341 | 
  Volume | 21.692119019828027 | 
}

Maybe you could update that class ?

**Comment by JKorf** [comment]
Hi, I've pushed an update to include the missing fields. Let me know if you find anything else missing.
