### ISSUE TITLE
GetAccountHistoryAsync with transactionTypes error

### ISSUE THREAD

**Issue by GarmashovK** [JKorf/Huobi.Net#42]
I try to get account history filtered by transaction types. My request:`var task = client.GetAccountHistoryAsync(acc.Id, startTime: DateTime.Now.AddDays(-30),
                        transactionTypes: new List<HuobiTransactionType> { HuobiTransactionType.DepositWithdraw });`.
As a result i've got a error: `Server error: base-argument-type-enum-unsupported, base argument type unsupported {0}`

**Comment by JKorf** [comment]
Should be fixed in the latest version; the mapping wasn't correct for the transaction type enum.
(Note that withdraw and deposit have been split)
