### ISSUE TITLE
Websocket Best Bid/Ask missing

### ISSUE THREAD

**Issue by Gustavobbr** [JKorf/Huobi.Net#43]
Hello JKorf,

initially let me take this opportunity to thank for the great work done.

While coding, I've noticed that the the websocket for best Bid/ask is missing.
https://huobiapi.github.io/docs/spot/v1/en/#best-bid-offer

Appreciate if it could be implemented.

Best Regards,

**Comment by JKorf** [comment]
Hi, It's been added and pushed to Nuget. Let me know if you need any other missing endpoints.

**Comment by Mkey85** [comment]
There is an issue with this endpoint.

`symbol = symbol.ValidateHuobiSymbol();`

is missing in the SubscribeToBestOfferUpdatesAsync method and causes issues with upper- and lowercase symbol parameters.
