### ISSUE TITLE
Websocket 'Asset and Order (v2)' missing

### ISSUE THREAD

**Issue by Gustavobbr** [JKorf/Huobi.Net#44]
Hello Jkorf,

There's this new version of websocket for Asset and Order that I couldn't find at the library
https://huobiapi.github.io/docs/spot/v1/en/#websocket-asset-and-order-v2

Could that be implemented ?

**Comment by JKorf** [comment]
Account socket subscriptions has been updated to the V2 API in 2.1.0.
