### ISSUE TITLE
Change methods SendHuobiRequest, SendHuobiTimestampRequest and SendHuobiV2Request to protected for easier extension.

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/Huobi.Net#51]
Currently this three methods are `private`. So we cannot create a class derived from `HuobiClient `that use them.
If you change the protection to `protected `, it will be possible to create a class derived from `HuobiClient` that implement other end-points, like [https://api.huobi.pro/v2/account/deposit/address](url).

**Comment by JKorf** [comment]
I'd rather have any endpoints missing being added in the client itself so it is available for anyone. Pull requests are welcome ;)

**Comment by EricGarnier** [comment]
OK
#53 
Some new endpoints
