### ISSUE TITLE
next-time field missing from result of GetHistoryOrdersAsync

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/Huobi.Net#53]
Hi @JKorf ,
the `GetHistoryOrdersAsync `api returns an `IEnumerable `of `HuobiOrder`. But for pagination purpose, a `next-time` is also returned by the server, when the query return to much data. Unfortunately, this field is not part of the `data` field, but after.
Here a sample : `{"status":"ok","data":[{"id":180316741408065,"symbol":"zenbtc","account-id":12156447,"client-order-id":"","amount":"4.760000000000000000","price":"0.000419830000000000","created-at":1609685999833,"type":"sell-limit","field-amount":"0.0","field-cash-amount":"0.0","field-fees":"0.0","finished-at":1609686002967,"source":"spot-api","state":"canceled","canceled-at":1609686002959}, .... ],"next-time":1609684257688}`.
What is the best way to implement this?
I can change the return value of the API to return an object with this field and an `IEnumerable`. Something like `GetTickersAsync` 
Do you have a better idea?

Thanks.
Eric

**Comment by JKorf** [comment]
Hm it's annoying that the field isn't part of the regular 'data' field, however it is understandable from a data point of view. I don't think there is much choice, there would need to be a wrapper object as you suggested.

**Comment by EricGarnier** [comment]
Here it is.
#54
