### ISSUE TITLE
 “HuobiClient”未包含“GetMarketDetails24H”的定义，并且找不到可接受第一个“HuobiClient”类型参数的可访问扩展方法“GetMarketDetails24H”(是否缺少 using 指令或程序集引用?) 

### ISSUE THREAD

**Issue by godpowerscn** [JKorf/Huobi.Net#56]
can you help me?

**Comment by JKorf** [comment]
You're trying to call GetMarketDetails24H, but that isn't a method on the HuobiClient.

**Comment by godpowerscn** [comment]
but example code has this method,so i use it ,but it does not work.

**Comment by JKorf** [comment]
The example code is in the documentation for the base library, which has multiple implementations. The example is for the Binance implementation. For Huobi use the GetTickers method. 

I suggest you use intellisense in Visual studio (or some other code suggestion tool) to see what methods are available.

**Comment by godpowerscn** [comment]
thanks a lot
