### ISSUE TITLE
Strange Behavior when using request from SocketClient

### ISSUE THREAD

**Issue by Gustavobbr** [JKorf/Huobi.Net#62]
Hi there,

First I'd like to cheer for the great work done.

When sending a request trough the SocketClient, if I get a ping message from Huobi **before** the message itself from the request, the variable "result.Data" return null.

Is there any treatment I can do in order to avoid that ?

Best Regards,

**Comment by JKorf** [comment]
Could you provide some debug logging? I'll look into it.
