### ISSUE TITLE
Cant find subscription to liquidation websocket

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Huobi.Net#64]
Hi,
according to the [api-doc](https://huobiapi.github.io/docs/dm/v1/en/#future-websocket-reference), there is a liquidation websocket available.

Somehow i couldn't find the function to subscribe to that websocket, like i did in binance.net or bitmex.net :)
How is it working in here?

Kind regards and thanks in advance for help
Amannda

**Comment by Amannda123** [comment]
i searched the repositoy for "liquidation_orders"  which seems to be the topic to subscribe to, but didnt got any result

https://huobiapi.github.io/docs/dm/v1/en/#subscribe-liquidation-order-data-no-authentication-sub

**Comment by JKorf** [comment]
The Futures API is not (yet) supported on Huobi. It is my intention to implement, but it is quite a lot of work and my time is limited, so unfortunately I'm not able to give any timeline on this.

**Comment by Amannda123** [comment]
Well maybe its not fully available but that websocket deffo is, but i totally understand your statement work-wise also no be able to give any eta :)  so i'll just be patient and checking back once a while..

thanks and thank you for the work you do 👍
