### ISSUE TITLE
Mutile-thread problem (SafeHandle cannot be null)

### ISSUE THREAD

**Issue by mzhou2018** [JKorf/Huobi.Net#7]
I got a "SafeHandle cannot be null" error while trying to place 3 orders at a time. 

![image](https://user-images.githubusercontent.com/44281076/52839161-0f83d500-3130-11e9-850c-3fc00b06492c.png)

> System.ArgumentNullException
>   HResult=0x80004003
>   Message=SafeHandle cannot be null.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument, ExceptionResource resource)
>    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
>    at Interop.BCrypt.BCryptHashData(SafeBCryptHashHandle hHash, Byte& pbInput, Int32 cbInput, Int32 dwFlags)
>    at Internal.Cryptography.HashProviderCng.AppendHashData(ReadOnlySpan`1 source)
>    at Internal.Cryptography.HashProvider.AppendHashData(Byte[] data, Int32 offset, Int32 count)
>    at System.Security.Cryptography.HMACSHA256.HashCore(Byte[] rgb, Int32 ib, Int32 cb)
>    at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
>    at Huobi.Net.HuobiAuthenticationProvider.AddAuthenticationToParameters(String uri, String method, Dictionary`2 parameters, Boolean signed) in K:\Huobi.Net\HuobiAuthenticationProvider.cs:line 51
>    at Huobi.Net.HuobiClient.ConstructRequest(Uri uri, String method, Dictionary`2 parameters, Boolean signed) in K:\Huobi.Net\HuobiClient.cs:line 585
>    at CryptoExchange.Net.RestClient.<ExecuteRequest>d__24`1.MoveNext()

any advice? thank you.

**Comment by JKorf** [comment]
Hi, that would be a bug in the library. I've pushed a new version, so version 0.0.5 should work for you now.
Thanks for the report, and let me know if you have any other issues.
