### ISSUE TITLE
Wrong test for eventType in SubscribeToOrderUpdatesAsync

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/Huobi.Net#70]
Hi JKorf,
with the latest version, you changed the code in the method SubscribeToOrderUpdatesAsync line 266 from:
                var eventType = (string) data.Data["data"]["eventType"];

to 
               if (data.Data["data"] == null || data.Data["eventType"] == null)
  
Unfortunately, the eventType is not directely under Data.
I think the correct test is
 
              if (data.Data["data"] == null || data.Data["data"]["eventType"] == null)
  
Do you agree?

Eric

**Comment by EricGarnier** [comment]
Same player shoot again in SubscribeToOrderDetailsUpdatesAsync

Eric

**Comment by JKorf** [comment]
That's what you get for trying to resolve warnings I guess -_-
Thanks for the report, fixed it in the latest version

**Comment by JKorf** [comment]
Fixed
