### ISSUE TITLE
System.NullReferenceException in Huobi.Net.HuobiSymbolOrderBook.DoResyncAsync()

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/Huobi.Net#71]
Hi JKorf,
I got a crash when a socket on Huobi try to reconnect.
The stack I can collect is :
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Huobi.Net.HuobiSymbolOrderBook.DoResyncAsync()
   at CryptoExchange.Net.OrderBook.SymbolOrderBook.ResyncAsync()
   at CryptoExchange.Net.OrderBook.SymbolOrderBook.<StartAsync>b__68_2(TimeSpan time)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Before this, I got the following warning:

2021/10/04 16:48:58:734 | Warning | Huobi      | Huobi order book icxbtc connection lost
2021/10/04 16:48:58:734 | Information | Huobi      | Huobi order book icxbtc status changed: Synced => Reconnecting
2021/10/04 16:49:03:802 | Information | Huobi      | Huobi order book icxbtc status changed: Reconnecting => Syncing

Any idea what goes wrong?

Eric

**Comment by JKorf** [comment]
Hm no, I'm not sure. This works on my end, when I disconnect my connection while being subscribed it restores the connection and resyncs the book correctly. What parameters are you using for the book? Are you on the latest version?

**Comment by EricGarnier** [comment]
Version is 3.2.0.0.
Parameters for SymboOrderBook : Levels : 20

**Comment by JKorf** [comment]
I read over this while implementing the market-by-price streams, but the 5/20 level mbp streams are only available for these symbols:
btcusdt,ethusdt,xrpusdt,eosusdt,ltcusdt,etcusdt,adausdt,dashusdt,bsvusdt.

For other symbols you'll have to use the 150 level. See https://huobiapi.github.io/docs/spot/v1/en/#market-by-price-incremental-update
