### ISSUE TITLE
Missing websockets

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Huobi.Net#73]
Hi, 

i know you're time is limited and all that, but could you add the websocket for liquidation_orders?

https://huobiapi.github.io/docs/dm/v1/en/#subscribe-liquidation-order-data-no-authentication-sub

thanks in advance <3

**Comment by JKorf** [comment]
Hi, sorry for the late reply. 
This endpoint is part of the futures API which has not yet been implemented. The endpoint should be implemented with the rest of the futures API, but I can't give any timeline on that.
