### ISSUE TITLE
How do I get historical trades?

### ISSUE THREAD

**Issue by tobijuthomas** [JKorf/Huobi.Net#74]
Below call always giving me the last 61 days result. I am not able to get the trades which is older than 61 days even if we provide specific startTime and endTime.

                var dateFrom = DateTime.UtcNow.AddDays(-120);
                var callResult = await client.GetUserTradesAsync(symbol: "btcusdt", startTime: dateFrom);

Is this the correct way or Am I doing something wrong?

**Comment by JKorf** [comment]
https://huobiapi.github.io/docs/spot/v1/en/#search-match-results
Seems like you should be able to get info on the last 120 days, though only 48 hours at a time. If it's still not working, can you provide some trace logging?

**Comment by llerrowa** [comment]
I've have PR which addresses this here - https://github.com/JKorf/Huobi.Net/pull/80
