### ISSUE TITLE
GetMergedTickerAsync fails, due to ask is null

### ISSUE THREAD

**Issue by valvv** [JKorf/Huobi.Net#79]
**Describe the bug**

Deserialize JsonReaderException: Error reading JArray from JsonReader. Current JsonReader item is not an array: Null. Path 'tick.ask', line 1, position 241. Path: tick.ask, LineNumber: 1, LinePosition: 241, data: {
  "ch": "market.gmpdusdt.detail.merged",
  "status": "ok",
  "ts": 1640095296903,
  "tick": {
    "id": 21753,
    "version": 21753,
    "open": 0.055,
    "close": 0.55,
    "low": 0.055,
    "high": 0.55,
    "amount": 127761.0,
    "vol": 70180.00561259,
    "count": 589,
    "bid": [
      0.55,
      9033438.09
    ],
    "ask": null
  }

**To Reproduce**
First minutes after listing

**Expected behavior**
HuobiSymbolTickMerged.HuobiOrderBookEntry? BestAsk

**Comment by JKorf** [comment]
Has been fixed
