### ISSUE TITLE
HuobiOrderTrade can't define trade side (sell/buy)

### ISSUE THREAD

**Issue by JohnSilver9999** [JKorf/Huobi.Net#83]
Hi. I try to get user trades by **SpotApi.Trading.GetUserTradesAsync** and parse the result  **IEnumerable<HuobiOrderTrade>**
but **HuobiOrderTrade** doesn't have any proterty of trade direction (side)  - buy or sell. 
Before  (in 6 version) this data was in **OrderType** property like LimitBuy/LimitSell
Is it a bug?

**Comment by JKorf** [comment]
Seems like you're right. I've added it in as `Side` property in version 4.0.2. Should be available in a few minutes.
Let me know if you have any other issues

**Comment by JohnSilver9999** [comment]
tnx
