### ISSUE TITLE
The real data is in the error. What is the situation?

### ISSUE THREAD

**Issue by wecando168** [JKorf/Huobi.Net#86]
https://github.com/JKorf/Huobi.Net/blob/7d4387c6f684d1cb878f7c1cdba8d1a6a0f399ef/Huobi.Net/Clients/HuobiClient.cs#L56

internal async Task<WebCallResult<T>> SendHuobiV2Request<T>(RestApiClient apiClient, Uri uri, HttpMethod method, CancellationToken cancellationToken, Dictionary<string, object>? parameters = null, bool signed = false)
        {
            var result = await SendRequestAsync<HuobiApiResponseV2<T>>(apiClient, uri, method, cancellationToken, parameters, signed).ConfigureAwait(false);
            if (!result || result.Data == null)
                return result.AsError<T>(result.Error!);

            if (result.Data.Code != 200)
                return result.AsError<T>(new ServerError(result.Data.Code, result.Data.Message));

            return result.As(result.Data.Data);
        }
}

The returned value：
data = null
success = false
but responsestatusecode = OK
The real data is in the error. What is the situation?
![1651136602(1)](https://user-images.githubusercontent.com/17273297/165800721-a41be4a9-44e8-4c3a-ab1d-2137807b69d3.png)

**Comment by JKorf** [comment]
I think there is some error during deserialization, and the data you see is just the data in the error object for debugging purposes. Have a look at the Error.Message property

**Comment by wecando168** [comment]
This problem occurred when I implemented the following interface
https://huobiapi.github.io/docs/spot/v1/en/#cancel-conditional-orders-before-triggering
I haven't found the implementation of the interfaces of the following operations in your project
https://huobiapi.github.io/docs/spot/v1/en/#conditional-order
So I try to realize it myself, but the above situation appears. It seems that I'm not sure how to deal with this problem. I don't know when your project can be supported. Is it convenient to test it? Thank you very much

**Comment by wecando168** [comment]
I also know that the problem should be in the during deserialization, but it seems that I haven't found a solution
It would be perfect if your project could provide direct support
I look forward to seeing you provide relevant updates

**Comment by JKorf** [comment]
I've added support for this in the latest version

**Comment by wecando168** [comment]
Tested your update. It's normal now. Thank you
