### ISSUE TITLE
Can't request open orders based on only the account ID may not be necessary

### ISSUE THREAD

**Issue by wecando168** [JKorf/Huobi.Net#87]
https://github.com/JKorf/Huobi.Net/blob/c95c16f496733c4f92b46dd548743792201180be/Huobi.Net/Clients/SpotApi/HuobiClientSpotApiTrading.cs#L77
Query the official API document of Huobi. When the accountid is not empty but the symbol is empty, return the outstanding orders of all symbols under the current accountid. Neither accountid nor symbol is a required parameter. Confirm whether this function does not need this judgment

**Comment by JKorf** [comment]
You're right, I'll remove it in next version

**Comment by JKorf** [comment]
Fixed in latest version

**Comment by wecando168** [comment]
thank you
