### ISSUE TITLE
clientOrderId is Mandatory

### ISSUE THREAD

**Issue by wecando168** [JKorf/Huobi.Net#88]
https://github.com/JKorf/Huobi.Net/blob/284f4c0f899bd36410067389f95e7e83db403955/Huobi.Net/Clients/SpotApi/HuobiClientSpotApiTrading.cs#L232

**Comment by JKorf** [comment]
It is generated in the lib if not send: `{ "clientOrderId", clientOrderId ?? Guid.NewGuid().ToString() },`
