### ISSUE TITLE
"minepool" type is incorrectly returned as "spot" type

### ISSUE THREAD

**Issue by wecando168** [JKorf/Huobi.Net#90]
When using this method to return Account, the AccountID of "minepool" type returned by Huobi's official API was incorrectly returned as "spot" type, resulting in two "spot" type accounts under one UID
https://github.com/JKorf/Huobi.Net/blob/284f4c0f899bd36410067389f95e7e83db403955/Huobi.Net/Clients/SpotApi/HuobiClientSpotApiAccount.cs#L71

**Comment by JKorf** [comment]
I added some missing account types, so this issue should be fixed in the latest version
