### ISSUE TITLE
Login fails on when CultureInfo is fi-FI 

### ISSUE THREAD

**Issue by tapiolindqvist75** [JKorf/Huobi.Net#92]
Hi,

I didn't manage to call any Rest functions propably because my CultureInfo is fi-FI it specifies (even though it is incorrect intepretation by Microsoft), that DateSeparator and TimeSeparator both are dots.
Error from Huobi was 
{: api-signature-not-valid, Signature not valid: Invalid submission time or incorrect time format [无效的提交时间，或时间格式错误] }

Workaround which works (at least for fi-FI) is:
System.Globalization.CultureInfo cultureInfo = (System.Globalization.CultureInfo)Thread.CurrentThread.CurrentCulture.Clone();
cultureInfo.DateTimeFormat.TimeSeparator = ":";
Thread.CurrentThread.CurrentCulture = cultureInfo;

**Comment by JKorf** [comment]
Thanks for the detailed report, it should be fixed in the latest version.
