### ISSUE TITLE
How I can get trade data for multiple symbols in one shot?

### ISSUE THREAD

**Issue by zydjohnHotmail** [JKorf/Huobi.Net#94]
Hello:
I want to know if I can use one HTTP request to get trade data for multiple symbols, but not all the symbols.
For example, if I want to get trade information for 10 symbols in one HTTP request, something like this follow HTTP GET request:
https://api.huobi.pro/market/trade?symbol=atombtc&symbol=btcusdt
But the above request only return the first sybmol in the request.
I know I can send one request for each symbol, but can I send one request to get data for 10 or 20 symbols, I don't need all the symbols.
Please advise,
Thanks,

**Comment by JKorf** [comment]
This is not a question for this library but for the Huobi API team
