### ISSUE TITLE
How I can use Nuget package to get account balance?

### ISSUE THREAD

**Issue by zydjohnHotmail** [JKorf/Huobi.Net#95]
Hello:
I just create API keys for my Huobi account, and I want to use Nuget package: to get my account balance.
But I can’t find any code example. I am using C# on Windows 10.
Please show me some code example on how to use API keys to sign HTTP request and get my account balance.
Thanks,

**Comment by JKorf** [comment]
Installing a nuget package is explained in various tutorials
