### ISSUE TITLE
Fix GetClosedOrdersAsync() which requires unix time in milliseconds 

### ISSUE THREAD

**Issue by AndreyVasilchenko** [JKorf/Huobi.Net#96]
now:
            parameters.AddOptionalParameter("start-date", startTime?.ToString("yyyy-MM-dd"));
            parameters.AddOptionalParameter("end-date", endTime?.ToString("yyyy-MM-dd"));

need:
            parameters.AddOptionalParameter("start-time", DateTimeConverter.ConvertToMilliseconds(startTime));
            parameters.AddOptionalParameter("end-time", DateTimeConverter.ConvertToMilliseconds(endTime));

**Comment by JKorf** [comment]
Has been fixed
