### ISSUE TITLE
client.SpotApi.Account.GetCurrentFeeRatesAsync empty response

### ISSUE THREAD

**Issue by dkzkv** [JKorf/Huobi.Net#98]
**Describe the bug**
client.SpotApi.Account.GetCurrentFeeRatesAsync do not have the response, Data is null.
Thats happened because huobi exchange send back error code "200" as a string (I suppose its a bug on their site).
But one can solve this problem just by adding extra validation

internal async Task<WebCallResult<T>> SendHuobiRequest<T> ...
...
if (result.Data.ErrorCode != "200" && result.Data.ErrorCode != null)  //<- here 

**To Reproduce**
v2/reference/transact-fee-rate

**Comment by JKorf** [comment]
Has been fixed
